spring:
  datasource:
    url: jdbc:mysql://192.168.56.108:3306/morning_shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root