spring:
  redis:
    database: 0
    host: 192.168.56.108
    port: 6379
    password: 123456
    encode: UTF-8
    timeout:  6000
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 5
